[package]
name = "piltover"
version = "0.1.0"
edition = "2023_10"

[dependencies]
cairo_verifier = { git = "https://github.com/cartridge-gg/cairo-verifier" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.20.1" }
starknet = "2.5.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = true

